### ISSUE TITLE
Setup pull requests for this repo so that it requires approval

### ISSUE THREAD

**Issue by Rezokeun** [bennettapps/Budget-App#5]
Not sure if this is a setting or if I just completely forgot how to properly use git ;P

but I was able to do a git push origin into this repo without having to having a PR (pull request) done. Can you please change the repo to only allow pushes to happen after a PR has been approved?

If I did do something wrong that bypassed the PR workflow let me know...but I don't think I did...I think it needs to be setup?

**Comment by bennettapps** [comment]
I think I just fixed it, could you please verify?

**Comment by Rezokeun** [comment]
I was able to bypass the repo...my dev workflow:

git checkout [master]
git pull origin
git checkout [local branch]
git merge master
create a new text file in vim
git add [text file]
git commit -m [message]
git checkout [master]
git merge [local branch]
git push origin

If there's a step I'm missing let me know...but I'm pretty sure it shouldn't be like this since it could potentially blow up this repo if others were to commit to it.

**Comment by bennettapps** [comment]
Well I would have no idea if you’re missing a step because I’m new to this 😂 

I’ll see what I can do.

**Comment by Rezokeun** [comment]
Did you do the steps in the first search result on Google for my search?

https://www.google.com/search?q=how+to+mandate+pull+requests+in+github+repo&oq=how+to+mandate+pull+requests+in+github+repo&aqs=chrome..69i57j33.9692j1j7&sourceid=chrome&ie=UTF-8

**Comment by bennettapps** [comment]
Yes, I set it to the master branch.

**Comment by Rezokeun** [comment]
I'm not sure what level of user you put me in for this repo so check out the below page and quote to see if that helps? This is a pretty important thing to get cleared up so I definitely think it's worth it for you to try and troubleshoot.

> ✅ Do: enable branch protection to effectively prevent force pushing e.g. to prevent rewriting the commit history. Tip:check the box for Include administrators at the bottom of the page to also apply this setting to organization and repository administrators.


https://github.community/t5/Support-Protips/Best-practices-for-protected-branches/ba-p/10224

**Comment by bennettapps** [comment]
Ok. It applies to admins now.

**Comment by Rezokeun** [comment]
Nope didn't work, test2.txt is there. I think I may know why...it's probably the dev workflow. I'm not sure if I should fork or not haha. Read this and tell me what next steps should be: https://help.github.com/en/articles/about-collaborative-development-models

**Comment by bennettapps** [comment]
Here are the commands I just used to create a successful pull request:

cd [local repo clone]
git branch [new branch]
git push --set-upstream origin [new branch]
git checkout [new branch]
touch [test.txt]
git add [test.txt]
git commit -m [commit name]
git push

Let me know if this works for you!

**Comment by Rezokeun** [comment]
You can close this out now, I have to fork and do a PR now so you're good.
